services:
  app:
    build:
      context: .
    image: quickshare-app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/quickshare
      POSTGRES_USER: quickshare
      POSTGRES_PASSWORD: quickshare
#      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
#      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
#      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
#      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    depends_on:
      - postgres

  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: quickshare
      POSTGRES_USER: quickshare
      POSTGRES_PASSWORD: quickshare
    volumes:
      - postgres18-data:/var/lib/postgresql

volumes:
  postgres18-data:
