services:
  app:
    build:
      context: .
    image: quickshare-app:latest
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/quickshare
      DB_USER: quickshare
      DB_PASSWORD: quickshare
      AWS_REGION: ${AWS_REGION}
      AWS_KEY: ${AWS_KEY}
      AWS_SECRET: ${AWS_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: quickshare
      POSTGRES_USER: quickshare
      POSTGRES_PASSWORD: quickshare
    volumes:
      - postgres18-data:/var/lib/postgresql

volumes:
  postgres18-data:
