spring:
  application:
    name: quickshare
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_KEY}
        secret-key: ${AWS_SECRET}
      region:
        static: ${AWS_REGION}

app:
  jwt:
    secret-key: ${JWT_SECRET}
  s3:
    bucket: ${S3_BUCKET}
